package Vista;

import Controlador.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author diego
 */
public class VistaConexion extends javax.swing.JFrame {

    private String user;
    private String pass;

    /**
     * Creates new form VistaConexion
     *
     */
    public VistaConexion() {
        initComponents();
        jbEnter.setForeground(Color.BLACK);
        jbClose.setForeground(Color.WHITE);
        jbEnter.setBackground(Color.LIGHT_GRAY);
        jbClose.setBackground(Color.DARK_GRAY);
        jbEnter.setFont(new Font("Monospaced", Font.BOLD, 20));
        jbClose.setFont(new Font("Monospaced", Font.BOLD, 20));

        jeTitle.setForeground(Color.WHITE);
        jeUser.setForeground(Color.WHITE);
        jePass.setForeground(Color.WHITE);
        jeTitle.setFont(new Font("Monospaced", Font.BOLD, 30));
        jeUser.setFont(new Font("Monospaced", Font.BOLD, 24));
        jePass.setFont(new Font("Monospaced", Font.BOLD, 24));

        jfUser.setBackground(Color.LIGHT_GRAY);
        jfPass.setBackground(Color.LIGHT_GRAY);
        jfUser.setFont(new Font("Monospaced", Font.BOLD, 24));
        jfPass.setFont(new Font("Monospaced", Font.BOLD, 24));
        jfUser.setHorizontalAlignment(SwingConstants.CENTER);
        jfPass.setHorizontalAlignment(SwingConstants.CENTER);

        getContentPane().setBackground(Color.BLACK);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbEnter = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();
        jeTitle = new javax.swing.JLabel();
        jeUser = new javax.swing.JLabel();
        jePass = new javax.swing.JLabel();
        jfUser = new javax.swing.JTextField();
        jfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbEnter.setText("Entrar");
        jbEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnterActionPerformed(evt);
            }
        });

        jbClose.setText("Cancelar");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        jeTitle.setText("Bienvenido a \"Strength Haven\"");

        jeUser.setText("Usuario:");

        jePass.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jeTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jeUser)
                        .addGap(25, 25, 25)
                        .addComponent(jfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbEnter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbClose))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jePass)
                            .addGap(25, 25, 25)
                            .addComponent(jfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jeTitle)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jeUser)
                    .addComponent(jfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jePass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEnter)
                    .addComponent(jbClose))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnterActionPerformed
        user = jfUser.getText();
        pass = new String(jfPass.getPassword());
        jfUser.setText("");
        jfPass.setText("");
        if (!user.equals("") && !pass.equals("")) {
            ControladorConexion.nuevaSesion(this, user, pass);
        }
    }//GEN-LAST:event_jbEnterActionPerformed

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCloseActionPerformed

    public void close() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbEnter;
    private javax.swing.JLabel jePass;
    private javax.swing.JLabel jeTitle;
    private javax.swing.JLabel jeUser;
    private javax.swing.JPasswordField jfPass;
    private javax.swing.JTextField jfUser;
    // End of variables declaration//GEN-END:variables
}
