package Aplicacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.UIManager;
import org.hibernate.SessionFactory;

/**
 *
 * @author Diego Francisco Darias Pino
 */
public class MenuP2 extends javax.swing.JFrame {

    private static SessionFactory sessionFactory;

    /**
     * Creates new form MenuP2
     */
    public MenuP2(SessionFactory sf) {
        this.sessionFactory = sf;
        initComponents();
        jb11.setName("11");
        jb12.setName("12");
        jb13.setName("13");
        for (Component comp : this.getContentPane().getComponents()) {
            String nom = comp.getName();
            if (comp instanceof JButton && nom != null) {
                JButton jb = (JButton) comp;
                int num = Integer.parseInt(nom);
                if (num % 2 == 0) {
                    jb.setForeground(Color.BLACK);
                    jb.setBackground(Color.LIGHT_GRAY);
                } else {
                    jb.setForeground(Color.WHITE);
                    jb.setBackground(Color.DARK_GRAY);
                }
                jb.setFont(new Font("Monospaced", Font.BOLD, 24));
            }
        }
        getContentPane().setBackground(Color.BLACK);
        UIManager.put("OptionPane.messageFont", new Font("Monospaced", Font.BOLD, 24));
        UIManager.put("OptionPane.messageForeground", Color.LIGHT_GRAY);
        UIManager.put("OptionPane.buttonFont", new Font("Monospaced", Font.BOLD, 24));
        UIManager.put("Button.background", Color.LIGHT_GRAY);
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("TextField.font", new Font("Monospaced", Font.BOLD, 24));
        UIManager.put("TextField.background", Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb11 = new javax.swing.JButton();
        jb12 = new javax.swing.JButton();
        jb13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb11.setText("1. Alta de un socio");

        jb12.setText("2. Información de actividad");

        jb13.setText("3. Actividades de un socio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb12, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jb11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jb11)
                .addGap(52, 52, 52)
                .addComponent(jb12)
                .addGap(52, 52, 52)
                .addComponent(jb13)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb11;
    private javax.swing.JButton jb12;
    private javax.swing.JButton jb13;
    // End of variables declaration//GEN-END:variables
}
